name: Déploiement VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur le VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/R314-TP2
            git pull origin main
            /home/etudiant/.bun/bin/bun install
            /home/etudiant/.bun/bin/bun run --bun build
            sudo systemctl restart r314-tp2

